const FETCH_CAT = 'cat/FETCH_CAT';
const FETCH_CAT_ERROR = 'cat/FETCH_CAT_ERROR';
const RECEIVE_CAT_SUCCESS = 'cat/RECEIVE_CAT_SUCCESS';
const RECEIVE_CAT_FAILURE = 'cat/RECEIVE_CAT_FAILURE';

export default {
  FETCH_CAT,
  FETCH_CAT_ERROR,
  RECEIVE_CAT_SUCCESS,
  RECEIVE_CAT_FAILURE,
};
